#AWS_PROFILE: external-test
PLATFORM: coralogix
CX_ENDPOINT: AP1
CLOUD_PROVIDER: GCP
CX_API_KEY: cxtp_iTZlQKzeoJ6kcsfmBdNJAVNhuhCuMp
REGIONS:
#  - eu-west-1
SERVICES:
#  - ec2
#  - test
  - logging
#  - compute_engine
  - cloud_storage